#!/usr/bin/env bash
# release — the release made mechanical, never taken.
#   bash release.sh              build the wheel and the sdist into dist/ with the project's own
#                                interpreter, run `twine check` on both, regenerate CHANGELOG.md
#   bash release.sh --changelog  regenerate CHANGELOG.md from RECON.md's section titles only
#   bash release.sh --check      refuse when CHANGELOG.md is not byte-identical to what RECON derives
# Publishing is the operator's one command, printed at the end and never run here.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The interpreter: PYTHON, else the project's .venv, else python3 (the changelog needs only the
# standard library; the build needs build+twine and refuses by name without them).
PY="${PYTHON:-}"
[ -n "$PY" ] || { [ -x "$HERE/.venv/bin/python" ] && PY="$HERE/.venv/bin/python" || PY="python3"; }
VERSION="$(grep -E '^version = ' "$HERE/engine/pyproject.toml" | sed -E 's/version = "(.*)"/\1/')"

changelog() {
    "$PY" - "$HERE/RECON.md" "$VERSION" <<'PY'
import re, sys
from pathlib import Path
recon, version = Path(sys.argv[1]).read_text(encoding="utf-8"), sys.argv[2]
rows = re.findall(r"^## (\d+) · (.+?) \((\d{4}-\d{2}-\d{2})(?: · (?:graphyos )?issue (\d+))?\)\s*$", recon, re.M)
out = [f"# graphyos — the changelog, derived from RECON.md", "",
       "Every line is a RECON section: the number re-derives it, the issue carries the evidence.",
       "Regenerated by `bash release.sh --changelog`; the gate refuses drift.", "",
       f"## {version}", ""]
for n, title, date, issue in reversed(rows):
    ref = f" (graphyos #{issue})" if issue and int(n) >= 39 else (f" (#{issue})" if issue else "")
    out.append(f"- §{n} · {date} — {title}{ref}")
print("\n".join(out) + "\n", end="")
PY
}

# The version lives once, in pyproject.toml; the plugin manifest and the registry entry repeat it
# and drift is refused here (graphyos #49) — never a second literal a hand forgot.
versions() {
    "$PY" - "$HERE" "$VERSION" <<'PYV'
import json, sys
from pathlib import Path
root, version = Path(sys.argv[1]), sys.argv[2]
plugin = json.loads((root / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8"))
server = json.loads((root / "server.json").read_text(encoding="utf-8"))
market = json.loads((root / ".claude-plugin" / "marketplace.json").read_text(encoding="utf-8"))
(entry,) = market["plugins"]
found = {".claude-plugin/plugin.json": plugin["version"], "server.json": server["version"],
         "server.json packages[0]": server["packages"][0]["version"],
         ".claude-plugin/marketplace.json plugins[0]": entry["version"], ".claude-plugin/marketplace.json metadata": market["metadata"]["version"]}
drift = {k: v for k, v in found.items() if v != version}
if drift:
    sys.exit(f"VERSION DRIFT: pyproject.toml says {version}; " + "; ".join(f"{k} says {v}" for k, v in drift.items()))
print(f"versions           OK  ({version} in pyproject.toml, .claude-plugin/plugin.json, marketplace.json, server.json)")
# The registry's two doors (graphyos #54): the ownership proof lives in the README the wheel ships —
# the one pyproject names, never the repo's — as `mcp-name: <server name>` followed by a boundary;
# and the registry caps the description at 100 characters, server-side only, so it is measured here.
import re
pyproject = (root / "engine" / "pyproject.toml").read_text(encoding="utf-8")
readme_name = re.search(r'^readme = "(.+)"$', pyproject, re.M).group(1)
readme = (root / "engine" / readme_name).read_text(encoding="utf-8")
if not re.search(r"mcp-name: " + re.escape(server["name"]) + r"(?=\s|-->|<)", readme):
    sys.exit(f"MCP-NAME MISSING: engine/{readme_name} (the README the wheel ships) lacks `mcp-name: {server['name']}` — the registry's ownership proof")
if len(server["description"]) > 100:
    sys.exit(f"DESCRIPTION OVER CAP: server.json description is {len(server['description'])} characters; the registry refuses over 100")
print(f"registry           OK  (mcp-name in engine/{readme_name}, description {len(server['description'])} chars)")
PYV
}

case "${1:-}" in
    --changelog) changelog > "$HERE/CHANGELOG.md"; echo "CHANGELOG OK: $(grep -c '^- §' "$HERE/CHANGELOG.md") entries -> CHANGELOG.md"; exit 0 ;;
    --check)
        if [ ! -f "$HERE/CHANGELOG.md" ] || ! diff -q <(changelog) "$HERE/CHANGELOG.md" > /dev/null; then
            echo "CHANGELOG DRIFT: CHANGELOG.md differs from what RECON.md derives — bash release.sh --changelog" >&2; exit 1
        fi
        echo "changelog          OK"; versions; exit 0 ;;
    "") ;;
    *) echo "usage: release.sh [--changelog | --check]" >&2; exit 2 ;;
esac

versions
"$PY" -c "import build, twine" 2>/dev/null || { echo "RELEASE REFUSED: $PY lacks build/twine — $PY -m pip install build twine" >&2; exit 2; }
rm -rf "$HERE/dist"
"$PY" -m build --outdir "$HERE/dist" "$HERE/engine" > "$HERE/dist.log" 2>&1 || { tail -20 "$HERE/dist.log"; exit 1; }
rm -f "$HERE/dist.log"
"$PY" -m twine check "$HERE"/dist/*
changelog > "$HERE/CHANGELOG.md"
ls -1 "$HERE/dist"
echo "RELEASE OK: graphyos $VERSION built and checked in dist/; CHANGELOG.md regenerated"
echo "  publish (the operator's call, never run here):  $PY -m twine upload dist/*"
