#!/usr/bin/env bash
# release — the release made mechanical, never taken.
#   bash release.sh              build the wheel and the sdist into dist/ with the project's own
#                                interpreter, run `twine check` on both, regenerate CHANGELOG.md
#   bash release.sh --changelog  regenerate CHANGELOG.md from RECON.md's section titles only
#   bash release.sh --check      refuse when CHANGELOG.md is not byte-identical to what RECON derives
# Publishing is the operator's one command, printed at the end and never run here.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The interpreter: PYTHON, else the project's .venv, else python3 (the changelog needs only the
# standard library; the build needs build+twine and refuses by name without them).
PY="${PYTHON:-}"
[ -n "$PY" ] || { [ -x "$HERE/.venv/bin/python" ] && PY="$HERE/.venv/bin/python" || PY="python3"; }
VERSION="$(grep -E '^version = ' "$HERE/engine/pyproject.toml" | sed -E 's/version = "(.*)"/\1/')"

changelog() {
    "$PY" - "$HERE/RECON.md" "$VERSION" <<'PY'
import re, sys
from pathlib import Path
recon, version = Path(sys.argv[1]).read_text(encoding="utf-8"), sys.argv[2]
rows = re.findall(r"^## (\d+) · (.+?) \((\d{4}-\d{2}-\d{2})(?: · (?:graphyos )?issue (\d+))?\)\s*$", recon, re.M)
out = [f"# graphyos — the changelog, derived from RECON.md", "",
       "Every line is a RECON section: the number re-derives it, the issue carries the evidence.",
       "Regenerated by `bash release.sh --changelog`; the gate refuses drift.", "",
       f"## {version}", ""]
for n, title, date, issue in reversed(rows):
    ref = f" (graphyos #{issue})" if issue and int(n) >= 39 else (f" (#{issue})" if issue else "")
    out.append(f"- §{n} · {date} — {title}{ref}")
print("\n".join(out) + "\n", end="")
PY
}

case "${1:-}" in
    --changelog) changelog > "$HERE/CHANGELOG.md"; echo "CHANGELOG OK: $(grep -c '^- §' "$HERE/CHANGELOG.md") entries -> CHANGELOG.md"; exit 0 ;;
    --check)
        if [ ! -f "$HERE/CHANGELOG.md" ] || ! diff -q <(changelog) "$HERE/CHANGELOG.md" > /dev/null; then
            echo "CHANGELOG DRIFT: CHANGELOG.md differs from what RECON.md derives — bash release.sh --changelog" >&2; exit 1
        fi
        echo "changelog          OK"; exit 0 ;;
    "") ;;
    *) echo "usage: release.sh [--changelog | --check]" >&2; exit 2 ;;
esac

"$PY" -c "import build, twine" 2>/dev/null || { echo "RELEASE REFUSED: $PY lacks build/twine — $PY -m pip install build twine" >&2; exit 2; }
rm -rf "$HERE/dist"
"$PY" -m build --outdir "$HERE/dist" "$HERE/engine" > "$HERE/dist.log" 2>&1 || { tail -20 "$HERE/dist.log"; exit 1; }
rm -f "$HERE/dist.log"
"$PY" -m twine check "$HERE"/dist/*
changelog > "$HERE/CHANGELOG.md"
ls -1 "$HERE/dist"
echo "RELEASE OK: graphyos $VERSION built and checked in dist/; CHANGELOG.md regenerated"
echo "  publish (the operator's call, never run here):  $PY -m twine upload dist/*"
