"""harness — the compile step that turns an eaten store into the agent's hub.

After a repo has been eaten (the store exists), ``graphy harness`` writes the partition if the
tenant has none, generates the walk region of every arm, draws the pillars and each arm,
blasts each crown, writes the hub file ``GRAPH.md``, and installs thin pointers into the
checkout. Curated bytes win: an existing ``partition.json`` is left alone, a scaffold block
is created once, and a human ``CLAUDE.md`` / ``AGENTS.md`` that is not a graphy pointer is
never smashed. Generated bytes are deterministic given the same store and partition; a clock
lives only in the walk receipt.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

__all__ = ["HarnessError", "POINTER_MARK", "run", "render_graph_md", "install_pointer"]

ASCII_CAP = 88
POINTER_MARK = "This repo's agent hub is generated."


class HarnessError(RuntimeError):
    pass


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _rel_to_repo(path: Path, repo: Path) -> str:
    try:
        return path.resolve().relative_to(repo.resolve()).as_posix()
    except ValueError:
        return str(path)


def cap_ascii(text: str, cap: int = ASCII_CAP) -> str:
    """Cap each line so a markdown fence stays readable."""
    out = []
    for ln in text.splitlines():
        out.append(ln[: cap - 1] + "…" if len(ln) > cap else ln)
    return "\n".join(out)


def pointer_text(hub: str) -> str:
    return (
        "# This repo's agent hub is generated.\n"
        "\n"
        f"Read `{hub}` (or the tenant GRAPH.md path printed by harness).\n"
        "Open only the arm you are touching. Blast its crown before you edit.\n"
        "Do not dump every arm file into context.\n"
    )


def install_pointer(path: Path, hub: str) -> str:
    """Write a thin pointer. ``installed`` · ``replaced`` · ``unchanged`` · ``left-alone``."""
    new = pointer_text(hub)
    if path.is_file():
        text = path.read_text(encoding="utf-8")
        if POINTER_MARK not in text:
            return "left-alone"
        if text == new:
            return "unchanged"
        path.write_text(new, encoding="utf-8")
        return "replaced"
    path.write_text(new, encoding="utf-8")
    return "installed"


def render_graph_md(*, corpus: str, generation: str, cut_sha: str, rows: list[tuple[str, str]],
                    tenant: str, tenant_id: str, tenant_dir: str, repo: str) -> str:
    lines = [
        f"# GRAPH — arms for {corpus}",
        "",
        "Law: walk before you read. Do not load this whole tree into context.",
        "Open only the arm you are touching. Blast its crown before you edit.",
        "",
        f"Store: {generation}",
        f"Partition: {cut_sha}",
        "Drawn: drawings/pillars.svg",
        "",
        "## Arms",
        "",
        "| arm | crown | drawing | walk receipt |",
        "|-----|-------|---------|--------------|",
    ]
    for name, crown in rows:
        lines.append(f"| {name} | {crown or '—'} | drawings/{name}.svg | arms/{name}.walk.txt |")
    lines += [
        "",
        "## Commands",
        "",
        "```bash",
        f"graphy blast <crown> --tenant {tenant} --tenant-id {tenant_id}",
        f"graphy pillars --tenant {tenant} --tenant-id {tenant_id} --corpus {corpus} --against {tenant_dir}/partition.json",
        f"graphy arms --tenant {tenant} --tenant-id {tenant_id} --corpus {corpus} --partition {tenant_dir}/partition.json --dir {tenant_dir}/arms --verify",
        f"graphy harness --repo {repo}   # regenerate drawings + generated regions + this file",
        "```",
        "",
    ]
    return "\n".join(lines) + "\n"


def _render_walk_receipt(name: str, crown: str | None, blast, generation: str, at: str) -> str:
    lines = [
        f"WALK {name}",
        f"crown: {crown or '—'}",
        f"store: {generation}",
        f"at: {at}",
    ]
    if blast is None:
        lines.append("dependents: (no crown to blast)")
        return "\n".join(lines) + "\n"
    total = max(0, len(blast.reached) - 1)
    lines.append(f"dependents: {total} own={len(blast.own)} ring={len(blast.ring)}")
    lines.append("top:")
    rows = list(blast.own) + list(blast.ring)
    if not rows:
        lines.append("  (none)")
    else:
        for r in rows[:12]:
            via = f"  ◀─{r.relation}─ {r.via}" if r.via else ""
            lines.append(f"  hop{r.hop} {r.node}{via}")
    return "\n".join(lines) + "\n"


def _pick_corpus(roster: list[str], corpus: str | None) -> str:
    if corpus is None:
        if len(roster) != 1:
            raise HarnessError(
                f"the tenant holds {len(roster)} corpora ({', '.join(roster)}) — "
                f"name one with --corpus; a door never guesses")
        return roster[0]
    if corpus not in roster:
        raise HarnessError(f"{corpus!r} is not a corpus of this tenant ({', '.join(roster)})")
    return corpus


def _partition_and_proposal(store, corpus: str, tenant_dir: Path, log) -> tuple:
    from graphy import fanout
    from graphy import pillars as pillars_lane
    part_path = tenant_dir / "partition.json"
    proposal = None
    try:
        graph = pillars_lane.module_graph(store, corpus)
        proposal = pillars_lane.propose(graph)
        log(pillars_lane.render(proposal, graph))
    except pillars_lane.PillarsError as exc:
        if not part_path.is_file():
            raise HarnessError(f"no partition at {part_path} and the proposal is unanswerable ({exc})") from exc
        log(f"HARNESS: proposal unanswerable ({exc}); using curated partition")
    if part_path.is_file():
        log(f"HARNESS: partition left alone (curated) {part_path}")
        cut = fanout.load_partition(part_path)
        what = "left-alone"
    else:
        doc = pillars_lane.to_partition(proposal)
        pillars_lane.write_partition(part_path, doc)
        cut = fanout.load_partition(part_path)
        log(f"HARNESS: partition wrote {part_path} — {len(doc['groups'])} group(s), rest={doc['rest']}")
        what = "wrote"
    return cut, proposal, what


def run(*, repo: str | Path, tenant, tenant_id: str, corpus: str | None = None,
        descriptor: str | Path, roster: list[str] | None = None,
        on_stale: str = "refuse", log=print) -> dict:
    """Compile the hub into the tenant directory (parent of the descriptor). ``tenant`` is the
    loaded Tenant; ``descriptor`` is its path, used in receipts and GRAPH.md commands."""
    from graphy import arms as arms_lane
    from graphy import doors
    from graphy import draw as draw_lane
    from graphy import federated_store as fstore
    from graphy.fanout import FanoutError

    repo = Path(repo).expanduser().resolve()
    if not repo.is_dir():
        raise HarnessError(f"not a directory: {repo}")
    desc = Path(descriptor).expanduser().resolve()
    tenant_dir = desc.parent
    if roster is None:
        from graphy import journal
        roster = sorted({journal._names(key)[1] for key in tenant.build_lanes})
    corpus = _pick_corpus(list(roster), corpus)
    try:
        store = fstore.open_for(roster, tenant=tenant, tenant_id=tenant_id, on_stale=on_stale)
    except (fstore.StoreError, AttributeError, TypeError, KeyError, OSError) as exc:
        raise HarnessError(f"{exc} — rebuild the store with `graphy build`") from exc

    try:
        cut, _proposal, part_what = _partition_and_proposal(store, corpus, tenant_dir, log)
    except FanoutError as exc:
        raise HarnessError(str(exc)) from exc
    if cut.groups is None:
        raise HarnessError("the partition is a depth cut — harness needs named arms")

    # The re-walk block's T= must match `graphy arms` (default tenants/<root name>), so
    # `arms --verify` after harness stays green. Eat's descriptor lives at <repo>/.graphy.
    if desc.name == "tenant.json" and desc.parent.name == ".graphy":
        tenant_dir_label = ".graphy"
    else:
        tenant_dir_label = f"tenants/{Path(tenant.root).name}"
    _inv, group_of, records = arms_lane._inventory(store, corpus, cut)
    _joins, crowns = arms_lane._joins_and_crowns(store, corpus, group_of, records)
    del _inv, _joins
    seeds = {}
    for name in cut.groups:
        crown = crowns.get(name)
        seeds[name] = {
            "crown": crown or "",
            "blast": (f"graphy blast {crown} --tenant {desc} --tenant-id {tenant_id}" if crown else ""),
        }

    try:
        regions = arms_lane.render_all(store, corpus, cut, tenant_dir=tenant_dir_label,
                                       tenant_id=tenant_id)
        done = arms_lane.generate(regions, tenant_dir / "arms", seeds=seeds)
    except arms_lane.ArmsError as exc:
        raise HarnessError(str(exc)) from exc
    log("HARNESS: arms " + " · ".join(f"{n} {w}" for n, w in done)
        + f" -> {tenant_dir / 'arms'}")

    drawings = tenant_dir / "drawings"
    drawings.mkdir(parents=True, exist_ok=True)
    reds: list[str] = []
    drawn: list[str] = []

    def _write_pic(pic, stem: str) -> None:
        for emit, ext in (("svg", ".svg"), ("html", ".html")):
            path = drawings / f"{stem}{ext}"
            red = draw_lane.emit_checked(pic, path, emit=emit, lr=True)
            tag = f"{stem}{ext}"
            if red:
                reds.append(f"{tag}: " + "; ".join(red))
                log(f"HARNESS: drawing {tag} CHECK RED " + "; ".join(red))
            else:
                drawn.append(tag)
                log(f"HARNESS: drawing {tag} CHECK GREEN")

    pic_p = draw_lane.pillars(store, corpus, cut)
    _write_pic(pic_p, "pillars")

    ascii_of: dict[str, str] = {}
    for name in cut.groups:
        try:
            pic = draw_lane.arm(store, corpus, cut, name)
        except draw_lane.DrawError as exc:
            log(f"HARNESS: drawing {name} skipped ({exc})")
            ascii_of[name] = f"(no drawing: {exc})"
            continue
        ascii_of[name] = cap_ascii(draw_lane.render(pic, emit="ascii", lr=True, color=False))
        _write_pic(pic, name)

    if reds:
        raise HarnessError("drawing check red — " + " · ".join(reds))

    at = _now()
    gen = store.generation()
    walk_rows: list[tuple[str, str]] = []
    for name in cut.groups:
        crown = crowns.get(name)
        blasted = None
        if crown and hasattr(store, "neighbours"):
            try:
                blasted = doors.blast(store, crown, max_depth=4)
            except (doors.DoorError, AttributeError, TypeError, KeyError) as exc:
                log(f"HARNESS: walk {name} skipped ({exc})")
        receipt = _render_walk_receipt(name, crown, blasted, gen, at)
        walk_path = tenant_dir / "arms" / f"{name}.walk.txt"
        walk_path.parent.mkdir(parents=True, exist_ok=True)
        walk_path.write_text(receipt, encoding="utf-8")
        n = max(0, len(blasted.reached) - 1) if blasted is not None else 0
        log(f"HARNESS: walk {name} crown={crown or '—'} dependents={n} → {walk_path}")
        walk_rows.append((name, crown or "—"))

        arm_md = tenant_dir / "arms" / f"{name}.md"
        what_draw = arms_lane.write_draw_band(arm_md, name, ascii_of.get(name, "(no drawing)"))
        what_scaf = arms_lane.ensure_scaffold(arm_md, name, seeds.get(name))
        log(f"HARNESS: arm {name} draw-band {what_draw} · scaffold {what_scaf}")

    cut_sha = f"sha256:{cut.sha256}" if cut.sha256 else "unpinned"
    graph_md = tenant_dir / "GRAPH.md"
    graph_md.write_text(render_graph_md(
        corpus=corpus, generation=gen, cut_sha=cut_sha, rows=walk_rows,
        tenant=str(desc), tenant_id=tenant_id, tenant_dir=str(tenant_dir), repo=str(repo),
    ), encoding="utf-8")
    log(f"HARNESS: GRAPH.md wrote {graph_md}")

    hub = _rel_to_repo(graph_md, repo)
    pointers = {}
    for fname in ("CLAUDE.md", "AGENTS.md"):
        what = install_pointer(repo / fname, hub)
        pointers[fname] = what
        if what == "left-alone":
            log(f"pointer not installed: existing {fname} left alone")
        else:
            log(f"HARNESS: pointer {fname} {what}")

    log(f"HARNESS OK: {len(list(cut.groups))} arm(s) store={gen} partition={cut_sha[:19]}… "
        f"→ {tenant_dir} (partition {part_what})")
    return {
        "corpus": corpus,
        "generation": gen,
        "cut": cut_sha,
        "tenant_dir": str(tenant_dir),
        "graph": str(graph_md),
        "hub": hub,
        "arms": [n for n, _w in done],
        "drawn": drawn,
        "pointers": pointers,
        "partition": part_what,
    }
