
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

from graphy.tenant import Tenant, TenantError, cli_tenant


def collect_substrates(data_root: Path) -> list[dict]:
    out: list[dict] = []
    if not data_root.exists():
        return out
    for child in sorted(data_root.iterdir()):
        if not child.is_dir() or not child.name.endswith("_graph"):
            continue
        stats_path = child / "stats.json"
        if not stats_path.exists():
            continue
        pkg = child.name[: -len("_graph")]
        stats = json.loads(stats_path.read_text(encoding="utf-8"))
        data_file = child / "nodes.json"
        built = (data_file if data_file.exists() else stats_path).stat().st_mtime
        out.append({
            "package": pkg,
            "graph_dir": str(child),
            "built": built,
            "nodes": stats.get("node_count", 0),
            "edges": stats.get("edge_count", 0),
            "clusters": stats.get("cluster_count", 0),
            "node_types": stats.get("node_types", {}),
            "edge_types": stats.get("edge_types", {}),
        })
    return out


def head_commit_time(repo_root: Path) -> float | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo_root), "log", "-1", "--format=%ct"],
            capture_output=True, text=True, timeout=10,
        )
        return float(out.stdout.strip()) if out.returncode == 0 else None
    except (OSError, ValueError, subprocess.SubprocessError):
        return None


def head_commit_sha(repo_root: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"[inventory] git rev-parse failed: {exc!r}", file=sys.stderr)
        return "UNKNOWN-git-unavailable"
    if out.returncode != 0:
        print(f"[inventory] git rev-parse rc={out.returncode}: "
              f"{out.stderr.strip()[:120]}", file=sys.stderr)
        return "UNKNOWN-not-a-git-repo"
    return out.stdout.strip() or "UNKNOWN-empty-sha"


def _fmt(epoch: float) -> str:
    return time.strftime("%Y-%m-%d %H:%M", time.gmtime(epoch))


def _render_overlay_section(lines: list, index: dict, tenant: Tenant) -> None:
    from graphy.augment_registry import (
        collect_augment_stamps, declared_from_stamp, observed_from_index)
    stamps = collect_augment_stamps(tenant=tenant)
    if not stamps:
        return
    lines.append("## Augments / no standalone graph (emit INTO other graphs — dir-scan-invisible)")
    lines.append("")
    lines.append("These substrates have **no `*_graph/` dir** — they emit `scheme://` nodes + typed edges INTO")
    lines.append("existing graphs (the live inventory above), so the dir-scan can't see them.")
    lines.append("**Declared** = the committed stamp's claim; **Observed** = the live member state (index-based).")
    lines.append("")
    lines.append("| Augment | Members | Join axes | Declared edge types (per member) | Observed | Blurb |")
    lines.append("|---|---|---|---|---|---|")
    for st in stamps:
        declared = declared_from_stamp(st)
        observed = observed_from_index(st, index)
        members = " ⊕ ".join(f"`{m}`" for m in st.get("members", [])) or "—"
        axes = " ".join(f"`{a}`" for a in st.get("join_keys", [])) or "—"
        det = " · ".join(f"`{m}`: {', '.join(d['edge_types'])}" for m, d in declared["members"].items()) or "—"
        obs = "✅ scheme_complete" if observed["scheme_complete"] else ("⚠ INCOMPLETE — " + "; ".join(observed["missing"]))
        cursors = ", ".join(f"{m}={c or '?'}" for m, c in observed["member_cursors"].items()) or "—"
        lines.append(f"| `{st['slug']}` | {members} | {axes} | {det} | {obs} (cursors: {cursors}) | {st.get('blurb', '')} |")
    lines.append("")


def render_markdown(substrates: list[dict], head_time: float | None = None, index: dict | None = None,
                    head_sha: str | None = None, *, tenant: Tenant | None = None) -> str:
    if tenant is None:
        raise ValueError("inventory.render_markdown: tenant is required — graphy resolves identity only "
                         "through a declared Tenant; absent tenant = refuse")
    lines: list[str] = []
    lines.append("# Substrate Inventory")
    lines.append("")
    lines.append("Auto-generated by the graphy inventory renderer.")
    lines.append("Do not edit by hand — re-run the inventory after building a new substrate.")
    lines.append("")
    lines.append(f"Inventory source_sha: {head_sha or 'UNKNOWN-not-supplied'}")
    if head_time is not None:
        lines.append(f"HEAD commit: {_fmt(head_time)} UTC")
    lines.append("")
    lines.append("## What this is")
    lines.append("")
    lines.append("Every directory under the tenant's `data_home/*_graph/` is an ingested **corpus**.")
    lines.append("")
    lines.append("## Live inventory")
    lines.append("")
    if not substrates:
        lines.append("_(no substrates built yet)_")
    else:
        lines.append("| Substrate | Nodes | Edges | Clusters | Built (UTC) |")
        lines.append("|---|---:|---:|---:|---|")
        total_nodes = 0
        total_edges = 0
        for s in substrates:
            built = _fmt(s["built"])
            lines.append(
                f"| `{s['package']}` | {s['nodes']:,} | {s['edges']:,} | {s['clusters']} | {built} |"
            )
            total_nodes += s["nodes"]
            total_edges += s["edges"]
        lines.append(f"| **TOTAL** | **{total_nodes:,}** | **{total_edges:,}** | | |")
        lines.append("")
        lines.append(f"**{len(substrates)} substrates, {total_nodes:,} nodes, {total_edges:,} edges.**")
    lines.append("")
    _render_overlay_section(lines, index or {}, tenant)
    lines.append("## Per-substrate breakdown")
    lines.append("")
    for s in substrates:
        lines.append(f"### `{s['package']}`")
        lines.append("")
        lines.append(f"- **Graph dir**: `{s['graph_dir']}`")
        lines.append(f"- **Built**: {_fmt(s['built'])} UTC (mtime of `nodes.json`)")
        lines.append(f"- **Nodes**: {s['nodes']:,}")
        lines.append(f"- **Edges**: {s['edges']:,}")
        lines.append(f"- **Clusters**: {s['clusters']}")
        lines.append("")
    lines.append("## Adding a new substrate")
    lines.append("")
    lines.append("```bash")
    lines.append("# 1. Confirm the package is installed")
    lines.append("python -c 'import <pkg>; print(\"ok\")'")
    lines.append("")
    lines.append("# 2. Ingest into the tenant data_home")
    lines.append("# 3. Regenerate this inventory")
    lines.append("python -m graphy.inventory --data-home <dh> --join-keys <jk> --tenant-id <id>")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


_cli_tenant = cli_tenant


def main(argv=None, *, tenant: Tenant | None = None) -> int:
    if tenant is None:
        ap = argparse.ArgumentParser(prog="inventory",
                                     description="render the gitignored substrate inventory report")
        ap.add_argument("--tenant-id", required=True,
                        help="the receipt-name — graphy resolves identity only through a declared Tenant.")
        ap.add_argument("--data-home", required=True,
                        help="the tenant data_home holding the `<slug>_graph` directories.")
        ap.add_argument("--join-keys", required=True,
                        help="path to the tenant's substrate_override_registry.json.")
        a = ap.parse_args(argv)
        try:
            tenant = _cli_tenant(a.data_home, a.join_keys, a.tenant_id)
        except TenantError as exc:
            print(f"INVENTORY REFUSED: {exc}", file=sys.stderr)
            return 2

    data_root = Path(tenant.data_home)
    out_path = data_root / ".SUBSTRATES.report.md"

    from graphy._portable_flock import fcntl
    lockf = data_root / ".SUBSTRATES.md.lock"
    lockf.touch(exist_ok=True)
    with open(lockf, "r+", encoding="utf-8") as lf:
        fcntl.flock(lf.fileno(), fcntl.LOCK_EX)
        try:
            substrates = collect_substrates(data_root)
            index: dict = {}
            index_path = data_root / ".federation_scheme_index.json"
            if index_path.exists():
                index = json.loads(index_path.read_text(encoding="utf-8"))
            md = render_markdown(substrates, head_commit_time(tenant.root), index,
                                 head_commit_sha(tenant.root), tenant=tenant)
            tmp = out_path.with_name(out_path.name + f".tmp.{os.getpid()}")
            tmp.write_text(md, encoding="utf-8")
            os.replace(tmp, out_path)
        finally:
            fcntl.flock(lf.fileno(), fcntl.LOCK_UN)
    print(f"[inventory] {len(substrates)} substrates → {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
